package data;

import java.math.BigInteger;
import java.security.SecureRandom;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class AccessToken {
    private AccessToken() { }

    static Map <String, Map<String,String>> accessTokenMap;
    private static int date;


    public static Map getAccessToken(){
        if (accessTokenMap ==null){
            accessTokenMap = new HashMap<String, Map<String, String>>();
            Map <String, String> temp = new HashMap<String, String>();
            try {
                Date d = new SimpleDateFormat("MM/dd/yyyy").parse("15/12/2018");
                date = (int) (d.getTime()/1000);
            } catch (ParseException e) {
                e.printStackTrace();
            }
            temp.put("name phone_num age_range gender photos", Integer.toString(date));
            accessTokenMap.put(generateTokenID(),temp);
        }
        return accessTokenMap;
    }

    static String generateTokenID(){


        /*
        This is how it is ideally done. For the moment just hardcoding with a value generated by this very code

        SecureRandom rnd = new SecureRandom();
        byte[] token = new byte[40];
        rnd.nextBytes(token);
        String tokenID = new BigInteger(1, token).toString(16);
        System.out.println(tokenID);

        */

        return "dafebe06c5c3ca986001aaa22bf1404253134440fd53bed99f2f58d1853a995fca9d7c9b999c3232";
    }


}
